# Generated by Django 4.2.17 on 2025-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edly_selfhosted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsurvey',
            name='load_form',
            field=models.BooleanField(default=True),
        ),
    ]
